### ISSUE TITLE
Hello, after I read the document, I still don't know how to run the command to get the cookies file.

### ISSUE THREAD

**Issue by MikuShare** [Tatsh/youtube-unofficial#3]
![image](https://user-images.githubusercontent.com/25380989/53958430-ff05bf80-411b-11e9-8f3c-7237d153b269.png)
I wrote the account password to the netrc file. This configuration is correct, but after I run this command, 1.txt is empty.

**Comment by Tatsh** [comment]
What is the output of `youtube-clear-watch-later --cookies 1.txt --debug`?

**Comment by MikuShare** [comment]
![image](https://user-images.githubusercontent.com/25380989/54012896-653d2180-41b2-11e9-9d15-80777c9f8941.png)
This is the ouput.
It seems to be a reminder that the file storing the cookies does not exist, but the file exists.

I would also like to ask, how do I use youtube-unofficial in other python files: X-YouTube-Client-Version, X-YouTube-Page-Label, X-YouTube-Page-CL, X-YouTube-Variants -Checksum, X-Youtube-Identity-Token.

**Comment by MikuShare** [comment]
I have a file that needs to use YouTube cookies, but I don't know how to log in to YouTube, youtube-unofficial can log in to YouTube, so I want to ask, what do I need to do to use the following parameters in other python files: cookies, X -YouTube-Client-Version, X-YouTube-Page-Label, X-YouTube-Page-CL, X-YouTube-Variants -Checksum, X-Youtube-Identity-Token.
Thank you very much!

**Comment by Tatsh** [comment]
Those are found by regex'ing the JS. I use BeatifulSoup4 to get the `<script>` tag.

See https://github.com/Tatsh/youtube-unofficial/blob/master/youtube_unofficial/__init__.py#L308

**Comment by MikuShare** [comment]
Ok, these seem like I can do it, but how do I log in to YouTube and get a cookie? Because if you want to get this information in the script tag, you must log in or use the cookie to access the page.

**Comment by Tatsh** [comment]
The [`#login()`](https://github.com/Tatsh/youtube-unofficial/blob/master/youtube_unofficial/__init__.py#L143) method. This is heavily based on youtube-dl's code.

**Comment by MikuShare** [comment]
I found a problem. When I ran youtube-clear-watch-later, my watch later: https://www.youtube.com/playlist?list=WL, there was still a video.

**Comment by Tatsh** [comment]
That's a known bug. Only the first page of videos is handled.

**Comment by MikuShare** [comment]
My watch later has only one video, but I still can't successfully clean this video, and I looked at the cookies, it seems to be invalid cookies.
![image](https://user-images.githubusercontent.com/25380989/54047743-d44a6280-4212-11e9-8f37-247c4b3f35d0.png)

**Comment by Tatsh** [comment]
Mine has these cookies. I do not know which ones are required.

```
ACCOUNT_CHOOSER
APISID
GAPS
HSID
LOGIN_INFO
LSID
NID
OSID
PREF
SAPISID
s_gl
SID
SIDCC
SSID
VISITOR_INFO1_LIVE
YSC
```

**Comment by MikuShare** [comment]
I mean youtube-unofficial can't log in normally. Can you check it out? I used -u -p and netrc files but they don't work. All kinds of signs indicate that I should not be logged into YouTube, so executing the command has no effect.

**Comment by Tatsh** [comment]
I just pushed some changes that should fix this as long as you are not using two-factor authentication. Please try that out.

**Comment by Tatsh** [comment]
And with the last commit just pushed 2FA should be working. SMS only.

**Comment by MikuShare** [comment]
![76EBE833-56F2-44B4-97ED-A7D3AC74EC7C](https://user-images.githubusercontent.com/25380989/54056092-06b38a00-422a-11e9-91a0-14b3587546d3.jpeg)
![528CB614-3A78-4ED6-96C2-2DC9A4E4D99B](https://user-images.githubusercontent.com/25380989/54056094-06b38a00-422a-11e9-8cd7-c6ed42710033.jpeg)
This is the result of running after I run git pull on two servers.

**Comment by MikuShare** [comment]
I am sure the password is correct.

**Comment by Tatsh** [comment]
Are you sure you have netrc formatted correctly?

```
machine youtube login xxxxxxxxx@gmail.com password thePasswordGoesHere
```

Your email might have a different domain and thats's okay.

**Comment by MikuShare** [comment]
I am very sure that my account password is ok.

**Comment by Tatsh** [comment]
Can you try passing arguments instead of netrc? I am not having any issues here with my file.

**Comment by MikuShare** [comment]
I just tried passing the parameters and I still prompted this. I can log in to Google on Chrome with my account password.

**Comment by Tatsh** [comment]
Do you have a regular Google account or an organisation account? Does your Google account use @gmail.com for email?

If you are on an organisation account, does that use a proxy to login?

I've had someone else verify this latest code with their non-2FA account and it worked for them.

**Comment by MikuShare** [comment]
I used three Google accounts and three servers, all of which prompted a password error.
My  Google account use @gmail.com for email.
Are my personal accounts.
And I turned off phone verification and 2FA.

**Comment by MikuShare** [comment]
Just now, I changed a server again, this time it was successful!

**Comment by MikuShare** [comment]
Finally, thank you for helping me, thank you very much.
